Car-Tracking-System-main/Car-Tracking/yazlab2/Controllers/MapCarsController.cs
using Google.Cloud.Firestore.V1;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using yazlab2.Models;
using Google.Cloud.Firestore;

namespace yazlab2.Controllers
{
    public class MapCarsController : Controller
    {
        string jsn = "yourjson";
        string projeId;
        private FirestoreDb firestoreDb;


        public MapCarsController()
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", jsn);
            projeId = "projectname";
            firestoreDb = FirestoreDb.Create(projeId);

        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]





        public async Task<IActionResult> Check(CarModel carmodel)
        {
            string markers = "[";
            //int idsend = (int)TempData["idsend"];

            List<DataModel> datalist = new List<DataModel>();
            int carId = carmodel.CarId;
            string time = carmodel.Time;
            string time2 = carmodel.Time2;
          



            CollectionReference docRef = firestoreDb.Collection("aracveri");
            Query query = docRef.WhereEqualTo("CarId", carId);
            QuerySnapshot querySnapshot = await query.GetSnapshotAsync();
            foreach (DocumentSnapshot documentSnapshot in querySnapshot.Documents)
            {
                Dictionary<string, object> dic = documentSnapshot.ToDictionary();
                string json = JsonConvert.SerializeObject(dic);
                DataModel data = JsonConvert.DeserializeObject<DataModel>(json);
                var timeData = DateTime.Parse(data.Time);
                var time3 = DateTime.Parse(time);
                var time4 = DateTime.Parse(time2);
                if (time3<=timeData && time4>=timeData)
                {
                    data.Id = documentSnapshot.Id;



                    datalist.Add(data);

                    markers += "{";

                    markers += string.Format("'Id': '{0}',", data.CarId);
                    markers += string.Format("'lat': '{0}',", data.Lang);
                    markers += string.Format("'lng': '{0}',", data.Lat);
                    markers += string.Format("'Time': '{0}'", data.Time);
                    markers += "},";

                }


            }


            markers += "];";
            ViewBag.Markers = markers;
            return View(datalist);


        }
    }
}

Car-Tracking-System-main/Car-Tracking/yazlab2/Controllers/MapController.cs
using Google.Cloud.Firestore;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using yazlab2.Models;

namespace yazlab2.Controllers
{
    public class MapController : Controller
    {
        string jsn = "./carsproject-343312-d8e6de01b9cb.json";
        string projeId;
        private FirestoreDb firestoreDb;
        public MapController()
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", jsn);
            projeId = "carsproject-343312";
            firestoreDb = FirestoreDb.Create(projeId);

        }

        public async Task<IActionResult> Index(string id)
        {
           
            string x = "2.10.2005 00:00:00";
            var time = DateTime.Parse(x);
            var time2 = DateTime.Parse(x);
            List<int> sayilar = new List<int>();
            sayilar.Add(0);
            int sayac = 0;
            List<DataModel> datalist = new List<DataModel>();
            string markers = "[";
            string[] stringArray = id.Split(',');
            int[] idler = new int[stringArray.Length];













            for (int i = 0; i < idler.Length; i++)
            {
                idler[i] = Convert.ToInt32(stringArray[i]);
            }


            for (int i = 0; i < idler.Length; i++)
            {
                CollectionReference docRef2 = firestoreDb.Collection("aracveri");
                Query query2 = docRef2.WhereEqualTo("CarId", idler[i]);
                QuerySnapshot querySnapshot2 = await query2.GetSnapshotAsync();
                foreach (DocumentSnapshot documentSnapshot in querySnapshot2.Documents)
                {
                    if (documentSnapshot.Exists)
                    {
                        Dictionary<string, object> dic = documentSnapshot.ToDictionary();
                        string json = JsonConvert.SerializeObject(dic);
                        DataModel data = JsonConvert.DeserializeObject<DataModel>(json);
                        data.Id = documentSnapshot.Id;


                        var timeData = DateTime.Parse(data.Time);

                        if(i == 0){
                            if (time < timeData)
                            {
                                time = timeData;

                            }
                        }
                        if (i == 1)
                        {
                            if (time2 < timeData)
                            {
                                time2 = timeData;

                            }
                        }





                    }
                }


                CollectionReference docRef = firestoreDb.Collection("aracveri");
                Query query = docRef.WhereEqualTo("CarId", idler[i]);
                QuerySnapshot querySnapshot = await query.GetSnapshotAsync();
                foreach (DocumentSnapshot documentSnapshot in querySnapshot.Documents)
                {
                    if (documentSnapshot.Exists)
                    {
                        Dictionary<string, object> dic = documentSnapshot.ToDictionary();
                        string json = JsonConvert.SerializeObject(dic);
                        DataModel data = JsonConvert.DeserializeObject<DataModel>(json);
                        //data.Id = documentSnapshot.Id;
                       

                        var timeData = DateTime.Parse(data.Time);
                       
                        var time3 = time.AddMinutes(-30);
                        var time4 = time2.AddMinutes(-30);

                        if (i == 0)
                        {
                            if (time3 < timeData)
                            {
                                data.Id = documentSnapshot.Id;

                                datalist.Add(data);

                                markers += "{";
                                markers += string.Format("'Id': '{0}',", data.CarId);
                                markers += string.Format("'lat': '{0}',", data.Lang);
                                markers += string.Format("'lng': '{0}',", data.Lat);
                                markers += string.Format("'Time': '{0}'", data.Time);
                                markers += "},";


                                for (int j = 0; j < sayilar.Count; j++)
                                {
                                    if (sayilar[j] == data.CarId)
                                    {
                                        sayac = 0;
                                    }
                                    else
                                    {
                                        sayac = 1;
                                    }
                                }
                                if (sayac > 0)
                                {
                                    sayilar.Add(Convert.ToInt32(data.CarId));
                                }

                            }
                        }
                        if (i == 1)
                        {
                            if (time4 < timeData)
                            {
                                data.Id = documentSnapshot.Id;

                                datalist.Add(data);

                                markers += "{";
                                markers += string.Format("'Id': '{0}',", data.CarId);
                                markers += string.Format("'lat': '{0}',", data.Lang);
                                markers += string.Format("'lng': '{0}',", data.Lat);
                                markers += string.Format("'Time': '{0}'", data.Time);
                                markers += "},";


                                for (int j = 0; j < sayilar.Count; j++)
                                {
                                    if (sayilar[j] == data.CarId)
                                    {
                                        sayac = 0;
                                    }
                                    else
                                    {
                                        sayac = 1;
                                    }
                                }
                                if (sayac > 0)
                                {
                                    sayilar.Add(Convert.ToInt32(data.CarId));
                                }
                            }
                        }
                      
                         
                    }
                }
            }

            markers += "];";
            ViewBag.idler = sayilar;
            ViewBag.Markers = markers;
            sayilar.RemoveAt(0);
            return View(sayilar);

        }
        
        public async Task<IActionResult> ShowDialogAsync(int id)
        {

            string x = "2.10.2005 00:00:00";
            var time = DateTime.Parse(x);
            List<CarModel> datalist = new List<CarModel>();
            CarModel model = new CarModel();
            CollectionReference docRef = firestoreDb.Collection("aracveri");
            Query query = docRef.WhereEqualTo("CarId", id);
            QuerySnapshot querySnapshot = await query.GetSnapshotAsync();
            foreach (DocumentSnapshot documentSnapshot in querySnapshot.Documents)
            {
                Dictionary<string, object> dic = documentSnapshot.ToDictionary();
                string json = JsonConvert.SerializeObject(dic);
                DataModel data = JsonConvert.DeserializeObject<DataModel>(json);
        
                var timeData = DateTime.Parse(data.Time);
               

                if (time < timeData)
                {
                    time = timeData;

                }
                var time2 = time.AddHours(-1);
                model.CarId = id;
                model.Time = time2.ToString();
                model.Time2 = time.ToString();

            }

            return PartialView("_MessageShow", model);

        }


    }
}

Car-Tracking-System-main/Car-Tracking/yazlab2/Views/Map/Index.cshtml
@using yazlab2.Models
@{ int a = 0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    
    <div id="dvMap" style="width: 900px; height: 600px;">
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDRPBZxDzHQ0fjp9oAdCvOBAAcrlqfeA4c"></script>
    <script type="text/javascript" src="./js/site.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script type="text/javascript">

         var markers = @Html.Raw(ViewBag.Markers);
        window.onload = function () {


            var mapOptions = {
                center: new google.maps.LatLng(markers[0].lat, markers[0].lng),
                zoom: 10,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            var map = new google.maps.Map(document.getElementById("dvMap"), mapOptions);
            for (i = 0; i < markers.length; i++) {
                var data = markers[i]
                var myLatlng = new google.maps.LatLng(data.lat, data.lng);
                if (data.Id == 1) {
                    var renk = "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
                }
                if (data.Id == 2) {
                    var renk= "http://maps.google.com/mapfiles/ms/icons/yellow-dot.png"
                }
                if (data.Id == 3) {
                    var renk = "http://maps.google.com/mapfiles/ms/icons/purple-dot.png"
                }
                if (data.Id == 4) {
                    var renk = "http://maps.google.com/mapfiles/ms/icons/green-dot.png"
                }
      

                var marker = new google.maps.Marker({
                    position: myLatlng,
                    map: map,
                    icon: {
                        url: renk
                    },
                    title: data.Id
                });
                (function (marker, data) {
                    google.maps.event.addListener(marker, "click", function (e) {
                        var infowindow = new google.maps.InfoWindow({
                            content: 'Time: ' + data.Time +
                                '<br>Latitude: ' + data.lat +
                                '<br>Longitude: ' + data.lng
                        });

                        infowindow.open(map, marker);
                    });

                })(marker, data);
            }
        }
    </script>
        </div>
    <div class="aracid" style=" top:-500px; left:20px; position:relative; ">

     
        @foreach (var carid in ViewBag.idler)
        {

<a class="btn btn-primary popup" style="background-color: lightblue;" data-url="@Url.Action("ShowDialog","Map",new {id=carid})" data-toggle="modal" data-target="#modal-create-edit-user" id="UserModel">  @carid Nolu Araç İçin Tıklayın <i class="fa fa-plus"></i></a>
                <partial name="_Modal" /><br><br>
                a = carid;

        }


        @section Scripts{
            <script src="~/js/User.js" asp-append-version="true"></script>

        }
        <button type="button" onclick="location.href='@Url.Action("Cikis","Login",new {id=@a})'" class="btn btn-primary" style="background-color: lightblue;float:right;color:black;">Çıkış</button>
    </div>







</body>
</html>

Car-Tracking-System-main/Car-Tracking/yazlab2/Views/Map/_MessageShow.cshtml
@model yazlab2.Models.CarModel

@{
    var data = ViewData["id"];
}

<div class="modal-content">

    <!--Modal Header Start-->
    <div class="modal-header">
        <h4 class="modal-title">Tarih Seç</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
    <!--Modal Header End-->



    @using (Html.BeginForm("Check", "MapCars", FormMethod.Post))
    {

        <div class="modal-body form-horizontal">
            

            
            <div class="col-sm-10">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="">Araba Id   </span>
                    <input asp-for="CarId" />
                </div>

                <div class="input-group-prepend">
                    <span class="input-group-text" id="">Başlangıç Saati   </span> 
                    <input asp-for="Time" />
                </div>
               

                <div class="input-group-prepend">
                    <span class="input-group-text" id="">Bitiş Saati   </span>
                    <input asp-for="Time2" />
                </div>
              

            </div>
            </div>


      
        <!--Modal Footer Start-->
        <div class="modal-footer">
            <button data-dismiss="modal" id="cancel" class="btn btn-default" type="button">Kapat</button>
            <td><button type="submit" value="Submit" />Getir</td>

        </div>
    }
    <!--Modal Footer End-->
  

</div>